from __future__ import annotations

from typing import Any, Protocol

import numpy as np


class H1Backend(Protocol):
    def start(self) -> None: ...

    def stop(self) -> None: ...

    def get_state(self) -> dict[str, Any]: ...

    def set_upper_body_joints(self, joints_hw: np.ndarray) -> None: ...

    def set_upper_body_joints_timed(self, joints_hw: np.ndarray, duration: float) -> None: ...

    def set_base_velocity(self, vx: float, vy: float, omega: float) -> None: ...

    def set_gripper(self, gripper: np.ndarray) -> None: ...